name: qintern-kagome-hva
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pytest
  - pip
  - pip:
      - qiskit
      - qiskit-aer
      - jupyter
      - notebook
